# Generated by Django 4.1.5 on 2023-06-06 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DNI", "DNI"),
                            ("Carnet de Extranjeria", "Carnet de Extranjeria"),
                            ("Pasaporte", "Pasaporte"),
                            ("Cedula de Identidad", "Cedula de Identidad"),
                            (
                                "Carnet de solicitante de refugio",
                                "Carnet de solicitante de refugio",
                            ),
                            ("Sin Documento", "Sin Documento"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "documento_identidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "apellido_paterno",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "apellido_materno",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("nombres", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "nombre_completo",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("telefono", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "correo_electronico",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "perfil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Administrador", "Administrador"),
                            ("Registrador", "Registrador"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("domicilio", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[("Masculino", "Masculino"), ("Femenino", "Femenino")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "estado_civil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Soltero", "Soltero"),
                            ("Casado", "Casado"),
                            ("Viudo", "Viudo"),
                            ("Divorciado", "Divorciado"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "unidad_ejecutora",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "unidad_organica",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "unidad_funcional",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "cargo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DIRECTOR/A GENERAL", "DIRECTOR/A GENERAL"),
                            ("DIRECTOR/A EJECUTIVO/A", "DIRECTOR/A GENERAL"),
                            ("DIRECTOR EJEC. ADJUNTO", "DIRECTOR EJEC. ADJUNTO"),
                            ("DIRECTOR SIST.ADM.I", "DIRECTOR SIST.ADM.I"),
                            ("MEDICO", "MEDICO"),
                            ("MEDICO I", "MEDICO I"),
                            ("MEDICO IV", "MEDICO IV"),
                            ("MEDICO ESPECIALISTA", "MEDICO ESPECIALISTA"),
                            ("ASIST. SOCIAL", "ASIST. SOCIAL"),
                            ("BIOLOGO", "BIOLOGO"),
                            ("BIOLOGO I", "BIOLOGO I"),
                            ("CIRUJANO DENTISTA", "CIRUJANO DENTISTA"),
                            ("ENFERMERA/O", "ENFERMERA/O"),
                            ("MEDICO VETERINARIO", "MEDICO VETERINARIO"),
                            ("NUTRICIONISTA", "NUTRICIONISTA"),
                            ("OBSTETRA", "OBSTETRA"),
                            ("PSICOLOGO", "PSICOLOGO"),
                            ("PSICOLOGO IV", "PSICOLOGO IV"),
                            ("QUIMICO FARMACEUTICO", "QUIMICO FARMACEUTICO"),
                            ("TECNOLOGO MEDICO", "TECNOLOGO MEDICO"),
                            ("ABOGADO I", "ABOGADO I"),
                            ("ABOGADO II", "ABOGADO II"),
                            ("ARQUITECTO IV", "ARQUITECTO IV"),
                            ("ASIST. ADMINIST. II", "ASIST. ADMINIST. II"),
                            ("ESP. ADMINIST. I", "ESP. ADMINIST. I"),
                            ("ESP. ADMINIST. II", "ESP. ADMINIST. II"),
                            ("ESP. ADMINIST. III", "ESP. ADMINIST. III"),
                            ("ESP. EN RACIONALIZ. II", "ESP. EN RACIONALIZ. II"),
                            ("ESTADISTICO II", "ESTADISTICO II"),
                            ("INGENIERO I", "INGENIERO I"),
                            ("INGENIERO II", "INGENIERO II"),
                            ("ARTESANO IV", "ARTESANO IV"),
                            ("CAJERO/A II", "CAJERO/A II"),
                            ("OPERAD. EQUIPO ELEC. II", "OPERAD. EQUIPO ELEC. II"),
                            ("OPERADOR P.A.D. I", "OPERADOR P.A.D. I"),
                            ("SECRETARIA III", "SECRETARIA III"),
                            ("SECRETARIA V", "SECRETARIA V"),
                            ("TEC. EN ABOGACIA II", "TEC. EN ABOGACIA II"),
                            ("TEC. EN ARCHIVO III", "TEC. EN ARCHIVO III"),
                            ("TEC. EN ENFERMERIA", "TEC. EN ENFERMERIA"),
                            ("TEC. EN ENFERMERIA I", "TEC. EN ENFERMERIA I"),
                            ("TEC. EN FARMACIA I", "TEC. EN FARMACIA I"),
                            ("TEC. EN TRANSPORTE II", "TEC. EN TRANSPORTE II"),
                            ("TEC. SANITARIO I", "TEC. SANITARIO I"),
                            ("ESP. EN SALUD OCUP. I", "ESP. EN SALUD OCUP. I"),
                            ("TECNICO/A ADMINIST. I", "TECNICO/A ADMINIST. I"),
                            ("TECNICO/A ADMINIST. II", "TECNICO/A ADMINIST. II"),
                            ("TECNICO/A ADMINIST. III", "TECNICO/A ADMINIST. III"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "condicion_laboral",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Nombrado", "Nombrado"),
                            ("Contrato Plazo Fijo", "Contrato Plazo Fijo"),
                            ("Contrato Plazo Indet.", "Contrato Plazo Indet."),
                            ("Contrato-CAS", "Contrato-CAS"),
                            ("Destacado Externo", "Destacado Externo"),
                            (
                                "CONTRAT. P.S./CAS ASISTENCIAL",
                                "CONTRAT. P.S./CAS ASISTENCIAL",
                            ),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "regimen_laboral",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("D.L. 1057-D.Leg 1057", "D.L. 1057-D.Leg 1057"),
                            ("Nombrado", "Nombrado"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "horario_ingreso",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "horario_receso",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "horario_reingreso",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "horario_salida",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True,
                        choices=[("Activo", "Activo"), ("Inactivo", "Inactivo")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "cuenta_usuario",
                    models.CharField(
                        blank=True,
                        choices=[("Si", "Si"), ("No", "No")],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("foto", models.ImageField(blank=True, null=True, upload_to="img")),
                (
                    "rol_unidad_organica",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "rol_empleado",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("rol_jefe", models.CharField(blank=True, max_length=200, null=True)),
                ("rol_rrhh", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "rol_vigilante",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Filiacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provincia", models.CharField(blank=True, max_length=100, null=True)),
                ("distrito", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "tipo_municipalidad",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Provincial", "Provincial"),
                            ("Distrital", "Distrital"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "documento_identidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "apellido_paterno",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "apellido_materno",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("nombres", models.CharField(blank=True, max_length=200, null=True)),
                ("telefono", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "correo_electronico",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "perfil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Administrador", "Administrador"),
                            ("Registrador", "Registrador"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "condicion",
                    models.CharField(
                        blank=True,
                        choices=[("Alta", "Alta"), ("Baja", "Baja")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "cuenta_usuario",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Si", "Si"),
                            ("No", "No"),
                            ("Espera respuesta MINSA", "Espera respuesta MINSA"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contraseña_usuario",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "req_formato",
                    models.FileField(
                        blank=True, null=True, upload_to="filiacion/formato/"
                    ),
                ),
                (
                    "dateTimeOfUpload_req_formato",
                    models.DateTimeField(auto_now=True, null=True),
                ),
                (
                    "req_generales_excel",
                    models.FileField(
                        blank=True, null=True, upload_to="filiacion/excel/"
                    ),
                ),
                (
                    "dateTimeOfUpload_generales_excel",
                    models.DateTimeField(auto_now=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportaMarcador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Tipo_documento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "documento_identidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "apellido_paterno",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "apellido_materno",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("nombres", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "nombre_completo",
                    models.CharField(blank=True, max_length=205, null=True),
                ),
                ("telefono", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "correo_electronico",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "fecha_nacimiento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cargo", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "regimen_laboral",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "fecha_ingreso",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("DNI", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nombre_completo2",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("fecha", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "horario_ingreso",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "horario_receso",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "horario_reingreso",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "horario_salida",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("Hora_00_06", models.CharField(blank=True, max_length=100, null=True)),
                ("Hora_06_07", models.CharField(blank=True, max_length=100, null=True)),
                ("Hora_07_08", models.CharField(blank=True, max_length=100, null=True)),
                ("Hora_08_09", models.CharField(blank=True, max_length=100, null=True)),
                ("Hora_09_10", models.CharField(blank=True, max_length=100, null=True)),
                ("Hora_10_11", models.CharField(blank=True, max_length=100, null=True)),
                ("Hora_11_12", models.CharField(blank=True, max_length=100, null=True)),
                ("Hora_12_13", models.CharField(blank=True, max_length=100, null=True)),
                ("Hora_13_14", models.CharField(blank=True, max_length=100, null=True)),
                ("Hora_14_15", models.CharField(blank=True, max_length=100, null=True)),
                ("Hora_15_16", models.CharField(blank=True, max_length=100, null=True)),
                ("Hora_16_17", models.CharField(blank=True, max_length=100, null=True)),
                ("Hora_17_18", models.CharField(blank=True, max_length=100, null=True)),
                ("Hora_18_19", models.CharField(blank=True, max_length=100, null=True)),
                ("Hora_19_20", models.CharField(blank=True, max_length=100, null=True)),
                ("Hora_20_21", models.CharField(blank=True, max_length=100, null=True)),
                ("Hora_21_22", models.CharField(blank=True, max_length=100, null=True)),
                ("Hora_22_23", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "estado_ingreso",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_salida",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_asistencia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hora_ingreso_marcador",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hora_salida_marcador",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("anio", models.CharField(blank=True, max_length=100, null=True)),
                ("mes", models.CharField(blank=True, max_length=100, null=True)),
                ("dia", models.CharField(blank=True, max_length=100, null=True)),
                ("Duracion", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_provincia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ubigeo", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Red",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_red",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "cod_red",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tardanza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("tardanza", models.DurationField()),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filiacion.empleado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PapeletaHora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "documento_identidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nombre_completo",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("cargo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "condicion_laboral",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "regimen_laboral",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "unidad_organica",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "fecha_papeleta_hora",
                    models.DateField(blank=True, max_length=100, null=True),
                ),
                ("anio", models.CharField(blank=True, max_length=100, null=True)),
                ("mes", models.CharField(blank=True, max_length=100, null=True)),
                ("dia", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "hora_salida",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "hora_retorno",
                    models.TimeField(blank=True, max_length=100, null=True),
                ),
                (
                    "hora_salida_marcador",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hora_retorno_marcador",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COMISION", "COMISION"),
                            ("SALUD", "SALUD"),
                            ("PARTICULAR", "PARTICULAR"),
                            ("CITACION JUDICIAL", "CITACION JUDICIAL"),
                        ],
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "fundamentacion",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "lugar_destino",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "estado_papeleta_dia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_papeleta_jefe",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_papeleta_rrhh",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_vigilante",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_final",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "rol_unidad_organica",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "rol_empleado",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("rol_jefe", models.CharField(blank=True, max_length=100, null=True)),
                ("rol_rrhh", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "rol_vigilante",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PapeletaDia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "documento_identidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nombre_completo",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("cargo", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "condicion_laboral",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "regimen_laboral",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "unidad_organica",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "fecha_papeleta_dia",
                    models.DateField(blank=True, max_length=100, null=True),
                ),
                ("anio", models.CharField(blank=True, max_length=100, null=True)),
                ("mes", models.CharField(blank=True, max_length=100, null=True)),
                ("dia", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "motivo",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "COMPENSACION DE HORAS EXTRAORDINARIAS",
                                "COMPENSACION DE HORAS EXTRAORDINARIAS",
                            ),
                            ("DESCANSO POR ONOMASTICO", "DESCANSO POR ONOMASTICO"),
                            (
                                "DEDUCIBLE DE VACACIONES DEL AÑO",
                                "DEDUCIBLE DE VACACIONES DEL AÑO",
                            ),
                            (
                                "LICENCIA POR CAPACITACION OFICIAL",
                                "LICENCIA POR CAPACITACION OFICIAL",
                            ),
                            (
                                "PERMISO POR DOCENCIA UNIVERSITARIA",
                                "PERMISO POR DOCENCIA UNIVERSITARIA",
                            ),
                            ("LICENCIA POR ENFERMEDAD", "LICENCIA POR ENFERMEDAD"),
                            (
                                "LICENCIA POR SEPELIO Y LUTO (FALLECIMIENTO)",
                                "LICENCIA POR SEPELIO Y LUTO (FALLECIMIENTO)",
                            ),
                            ("PERMISO SIN GOSE DE HABER", "PERMISO SIN GOSE DE HABER"),
                            ("POR COMISION DE SERVICIO", "POR COMISION DE SERVICIO"),
                            ("POR CITACION JUDICIAL", "POR CITACION JUDICIAL"),
                            ("POR LACTANCIA", "POR LACTANCIA"),
                            ("OTROS (ESPECIFICAR)", "OTROS (ESPECIFICAR)"),
                        ],
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "fundamentacion",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "fecha_inicio",
                    models.DateField(blank=True, max_length=100, null=True),
                ),
                ("fecha_fin", models.DateField(blank=True, max_length=100, null=True)),
                (
                    "duracion_dias",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_papeleta_dia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_papeleta_jefe",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_papeleta_rrhh",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_final",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Microred",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_microred",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cod_mic",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                (
                    "cod_red",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                (
                    "red",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redes",
                        to="filiacion.red",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarcadorEmpleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "documento_identidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nombre_completo",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("fecha", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "horario_ingreso",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "horario_receso",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "horario_reingreso",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "horario_salida",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_ingreso",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_salida",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_asistencia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hora_ingreso_marcador",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hora_salida_marcador",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hora_tolerancia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hora_tolerancia_tarde",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("anio", models.CharField(blank=True, max_length=100, null=True)),
                ("mes", models.CharField(blank=True, max_length=100, null=True)),
                ("dia", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "fecha_marcacion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "duracion_horas",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "duracion_minutos",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tardanza", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "tardanza_tarde",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "horario_ingreso",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "horario_receso",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "horario_reingreso",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "horario_salida",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("hora_entrada", models.TimeField()),
                ("hora_salida", models.TimeField()),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filiacion.empleado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Establecimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_establecimiento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "codigo_unico",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "microred",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="microredes",
                        to="filiacion.microred",
                    ),
                ),
                (
                    "red",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filiacion.red",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Distrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_distrito",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ubigeo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "provincia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provincias",
                        to="filiacion.provincia",
                    ),
                ),
            ],
        ),
    ]
