# Generated by Django 4.1.5 on 2023-06-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="papeletadia",
            name="rol_empleado",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="papeletadia",
            name="rol_jefe",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="papeletadia",
            name="rol_rrhh",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="papeletadia",
            name="rol_unidad_organica",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="papeletadia",
            name="rol_vigilante",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
