# Generated by Django 4.1.5 on 2023-05-17 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="unidad_organica",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="filiacion.red",
            ),
        ),
        migrations.AlterField(
            model_name="papeletahora",
            name="motivo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMISION", "COMISION"),
                    ("SALUD", "SALUD"),
                    ("PARTICULAR", "PARTICULAR"),
                    ("CITACION JUDICIAL", "CITACION JUDICIAL"),
                ],
                max_length=250,
                null=True,
            ),
        ),
    ]
