# Generated by Django 4.1.5 on 2023-02-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0002_empleado"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="foto",
            field=models.FileField(blank=True, null=True, upload_to="filiacion/excel/"),
        ),
    ]
