# Generated by Django 4.1.5 on 2023-05-18 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0003_empleado_rol_empleado_empleado_rol_jefe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="papeletahora",
            name="rol_empleado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="papeletahora_rol_empleado",
                to="filiacion.empleado",
            ),
        ),
        migrations.AddField(
            model_name="papeletahora",
            name="rol_jefe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="papeletahora_rol_jefe",
                to="filiacion.empleado",
            ),
        ),
        migrations.AddField(
            model_name="papeletahora",
            name="rol_rrhh",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="papeletahora_rol_rrhh",
                to="filiacion.empleado",
            ),
        ),
        migrations.AddField(
            model_name="papeletahora",
            name="rol_unidad_organica",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="papeletahora_rol_unidad_organica",
                to="filiacion.empleado",
            ),
        ),
        migrations.AddField(
            model_name="papeletahora",
            name="rol_vigilante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="papeletahora_vigilante",
                to="filiacion.empleado",
            ),
        ),
    ]
