# Generated by Django 4.1.5 on 2023-07-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "filiacion",
            "0003_empleado_auditoria_empleado_empleado_auditoria_jefe_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="papeletahora",
            name="estado_auditoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pendiente", "Pendiente"),
                    ("aprobada", "Aprobada"),
                    ("rechazada", "Rechazada"),
                    ("observado", "Observado"),
                    ("firmado", "Firmado"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="papeletahora",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="papeletahora",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="papeletahora",
            name="fecha_empleado",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="papeletahora",
            name="fecha_jefe",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="papeletahora",
            name="fecha_modificacion",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="papeletahora",
            name="fecha_rrhh",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="papeletahora",
            name="fecha_vigilante",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
