# Generated by Django 4.1.5 on 2023-02-09 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0004_alter_empleado_cargo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filiacion",
            name="perfil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Administrador", "Administrador"),
                    ("Registrador", "Registrador"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_marcacion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "horario_ingreso_marcacion",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "horario_receso_marcacion",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "horario_reingreso_marcacion",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "horario_salida_marcacion",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "documento_identidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documento_identidads",
                        to="filiacion.empleado",
                    ),
                ),
                (
                    "horario_ingreso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horario_ingresos",
                        to="filiacion.empleado",
                    ),
                ),
                (
                    "horario_receso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horario_recesos",
                        to="filiacion.empleado",
                    ),
                ),
                (
                    "horario_reingreso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horario_reingresos",
                        to="filiacion.empleado",
                    ),
                ),
                (
                    "horario_salida",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horario_salidas",
                        to="filiacion.empleado",
                    ),
                ),
            ],
        ),
    ]
