# Generated by Django 4.1.5 on 2023-05-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0004_papeletahora_rol_empleado_papeletahora_rol_jefe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="papeletahora",
            name="rol_empleado",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="papeletahora",
            name="rol_jefe",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="papeletahora",
            name="rol_rrhh",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="papeletahora",
            name="rol_unidad_organica",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="papeletahora",
            name="rol_vigilante",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
