# Generated by Django 4.1.5 on 2023-02-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0005_alter_filiacion_perfil_asistencia"),
    ]

    operations = [
        migrations.RemoveField(model_name="asistencia", name="horario_ingreso",),
        migrations.RemoveField(model_name="asistencia", name="horario_receso",),
        migrations.RemoveField(model_name="asistencia", name="horario_reingreso",),
        migrations.RemoveField(model_name="asistencia", name="horario_salida",),
    ]
