# Generated by Django 4.1.5 on 2023-08-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0005_papeletahora_estado_observacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="papeletadia",
            name="correo_electronico",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="papeletadia",
            name="telefono",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
