# Generated by Django 4.1.5 on 2023-05-18 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0006_alter_papeletahora_rol_unidad_organica"),
    ]

    operations = [
        migrations.AlterField(
            model_name="papeletahora",
            name="rol_unidad_organica",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="filiacion.red",
            ),
        ),
    ]
