# Generated by Django 4.1.5 on 2023-05-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0007_alter_papeletahora_rol_unidad_organica"),
    ]

    operations = [
        migrations.AlterField(
            model_name="papeletahora",
            name="rol_unidad_organica",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
