# Generated by Django 4.1.5 on 2023-05-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0008_alter_papeletahora_rol_unidad_organica"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="unidad_organica",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
