# Generated by Django 4.1.5 on 2023-02-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0008_rename_documento_identidad_asistencia_empleado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marcador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empleado", models.CharField(blank=True, max_length=100, null=True)),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
                ("marcacion", models.CharField(blank=True, max_length=100, null=True)),
                ("hora_00_06", models.CharField(blank=True, max_length=100, null=True)),
                ("hora_06_08", models.CharField(blank=True, max_length=100, null=True)),
                ("hora_08_09", models.CharField(blank=True, max_length=100, null=True)),
                ("hora_09_10", models.CharField(blank=True, max_length=100, null=True)),
                ("hora_10_11", models.CharField(blank=True, max_length=100, null=True)),
                ("hora_11_12", models.CharField(blank=True, max_length=100, null=True)),
                ("hora_13_14", models.CharField(blank=True, max_length=100, null=True)),
                ("hora_15_16", models.CharField(blank=True, max_length=100, null=True)),
                ("hora_17_18", models.CharField(blank=True, max_length=100, null=True)),
                ("hora_18_19", models.CharField(blank=True, max_length=100, null=True)),
                ("hora_19_20", models.CharField(blank=True, max_length=100, null=True)),
                ("hora_20_21", models.CharField(blank=True, max_length=100, null=True)),
                ("hora_21_22", models.CharField(blank=True, max_length=100, null=True)),
                ("hora_22_23", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
