# Generated by Django 4.1.5 on 2023-02-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0010_alter_marcador_empleado"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marcador", old_name="marcacion", new_name="fecha",
        ),
        migrations.AddField(
            model_name="marcador",
            name="hora_12_13",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="hora_14_15",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="hora_16_17",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
