# Generated by Django 4.1.5 on 2023-02-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "filiacion",
            "0011_rename_marcacion_marcador_fecha_marcador_hora_12_13_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="marcador",
            name="empleado",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
