# Generated by Django 4.1.5 on 2023-02-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0012_alter_marcador_empleado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marcador",
            name="nombre",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
