# Generated by Django 4.1.5 on 2023-02-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0013_alter_marcador_nombre"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marcador", old_name="empleado", new_name="DNI",
        ),
        migrations.RenameField(
            model_name="marcador", old_name="hora_00_06", new_name="Duracion",
        ),
        migrations.RenameField(
            model_name="marcador", old_name="hora_06_08", new_name="Hora_00_06",
        ),
        migrations.RenameField(
            model_name="marcador", old_name="hora_08_09", new_name="Hora_06_07",
        ),
        migrations.RenameField(
            model_name="marcador", old_name="hora_09_10", new_name="Hora_07_08",
        ),
        migrations.RenameField(
            model_name="marcador", old_name="hora_10_11", new_name="Hora_08_09",
        ),
        migrations.RenameField(
            model_name="marcador", old_name="hora_11_12", new_name="Hora_09_10",
        ),
        migrations.RenameField(
            model_name="marcador", old_name="hora_12_13", new_name="Hora_10_11",
        ),
        migrations.RenameField(
            model_name="marcador", old_name="hora_13_14", new_name="Hora_11_12",
        ),
        migrations.RenameField(
            model_name="marcador", old_name="hora_14_15", new_name="Hora_12_13",
        ),
        migrations.RenameField(
            model_name="marcador", old_name="hora_15_16", new_name="Hora_13_14",
        ),
        migrations.RenameField(
            model_name="marcador", old_name="hora_16_17", new_name="Hora_14_15",
        ),
        migrations.RenameField(
            model_name="marcador", old_name="hora_17_18", new_name="Hora_15_16",
        ),
        migrations.RenameField(
            model_name="marcador", old_name="hora_18_19", new_name="Hora_16_17",
        ),
        migrations.RenameField(
            model_name="marcador", old_name="hora_19_20", new_name="Hora_17_18",
        ),
        migrations.RenameField(
            model_name="marcador", old_name="hora_20_21", new_name="Hora_18_19",
        ),
        migrations.RenameField(
            model_name="marcador", old_name="hora_21_22", new_name="Hora_19_20",
        ),
        migrations.RenameField(
            model_name="marcador", old_name="hora_22_23", new_name="Hora_20_21",
        ),
        migrations.RemoveField(model_name="marcador", name="nombre",),
        migrations.AddField(
            model_name="marcador",
            name="Hora_21_22",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="Hora_22_23",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="Tipo_documento",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="anio",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="apellido_materno",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="apellido_paterno",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="cargo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="correo_electronico",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="dia",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="documento_identidad",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="estado_asistencia",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="estado_ingreso",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="estado_salida",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="fecha_ingreso",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="fecha_nacimiento",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="hora_ingreso_marcador",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="hora_salida_marcador",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="horario_ingreso",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="horario_receso",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="horario_reingreso",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="horario_salida",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="mes",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="nombre_completo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="nombre_completo2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="nombres",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="regimen_laboral",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcador",
            name="telefono",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(name="Asistencia",),
    ]
