# Generated by Django 4.1.5 on 2023-02-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0015_importamarcador_delete_marcador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importamarcador",
            name="apellido_materno",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="importamarcador",
            name="apellido_paterno",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="importamarcador",
            name="cargo",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="importamarcador",
            name="correo_electronico",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="importamarcador",
            name="nombre_completo",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="importamarcador",
            name="nombre_completo2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="importamarcador",
            name="nombres",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="importamarcador",
            name="regimen_laboral",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
