# Generated by Django 4.1.5 on 2023-02-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0017_alter_importamarcador_nombre_completo"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarcadorEmpleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DNI", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "documento_identidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nombre_completo",
                    models.CharField(blank=True, max_length=205, null=True),
                ),
                (
                    "nombre_completo2",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("fecha", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "hora_ingreso_marcador",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hora_salida_marcador",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("anio", models.CharField(blank=True, max_length=100, null=True)),
                ("mes", models.CharField(blank=True, max_length=100, null=True)),
                ("dia", models.CharField(blank=True, max_length=100, null=True)),
                ("Duracion", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
