# Generated by Django 4.1.5 on 2023-02-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0019_marcadorempleado_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marcadorempleado",
            old_name="Duracion",
            new_name="estado_asistencia",
        ),
        migrations.AddField(
            model_name="marcadorempleado",
            name="duracion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcadorempleado",
            name="estado_ingreso",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcadorempleado",
            name="estado_salida",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcadorempleado",
            name="tardanza",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="marcadorempleado",
            name="nombre_completo",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="marcadorempleado",
            name="nombre_completo2",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
