# Generated by Django 4.1.5 on 2023-02-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "filiacion",
            "0020_rename_duracion_marcadorempleado_estado_asistencia_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="horario_ingreso",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="horario_receso",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="horario_reingreso",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="horario_salida",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
