# Generated by Django 4.1.5 on 2023-02-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0021_empleado_horario_ingreso_empleado_horario_receso_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="filiacion/formato/"
            ),
        ),
    ]
