# Generated by Django 4.1.5 on 2023-02-17 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0025_marcadorempleado_fecha_marcacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="marcadorempleado",
            name="empleado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="filiacion.empleado",
            ),
        ),
    ]
