# Generated by Django 4.1.5 on 2023-02-17 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0026_marcadorempleado_empleado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marcadorempleado",
            name="empleado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="filiacion.empleado",
                to_field="documento_identidad",
            ),
        ),
        migrations.AddConstraint(
            model_name="empleado",
            constraint=models.UniqueConstraint(
                fields=("documento_identidad",), name="unique_documento_identidad"
            ),
        ),
    ]
