# Generated by Django 4.1.5 on 2023-02-17 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0027_alter_marcadorempleado_empleado_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="empleado", name="unique_documento_identidad",
        ),
        migrations.AlterField(
            model_name="marcadorempleado",
            name="empleado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="filiacion.empleado",
            ),
        ),
    ]
