# Generated by Django 4.1.5 on 2023-02-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0029_remove_marcadorempleado_empleado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marcadorempleado",
            name="hora_tolerancia_tarde",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="marcadorempleado",
            name="tardanza_tarde",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
