# Generated by Django 4.1.5 on 2023-02-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0030_marcadorempleado_hora_tolerancia_tarde_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="img"),
        ),
    ]
