# Generated by Django 4.1.5 on 2023-02-18 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("filiacion", "0031_alter_empleado_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="PapeletaHora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cargo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "unidad_organica",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "fecha_papeleta_hora",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("anio", models.CharField(blank=True, max_length=100, null=True)),
                ("mes", models.CharField(blank=True, max_length=100, null=True)),
                ("dia", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "hora_salida",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hora_retorno",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hora_salida_marcador",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hora_retorno_marcador",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PERSONAL", "PERSONAL"),
                            ("SALUD", "SALUD"),
                            ("PARTICULAR", "PARTICULAR"),
                            ("COMISION", "COMISION"),
                        ],
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "fundamentacion",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "estado_papeleta_dia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_papeleta_jefe",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_papeleta_rrhh",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_vigilante",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_final",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "documento_identidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filiacion.empleado",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PapeletaDia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cargo", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "unidad_organica",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "fecha_papeleta_dia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "COMPENSACION DE HORAS EXTRAORDINARIAS",
                                "COMPENSACION DE HORAS EXTRAORDINARIAS",
                            ),
                            ("DESCANSO POR ONOMASTICO", "DESCANSO POR ONOMASTICO"),
                            (
                                "DEDUCIBLE DE VACACIONES DEL AÑO",
                                "DEDUCIBLE DE VACACIONES DEL AÑO",
                            ),
                            (
                                "LICENCIA POR CAPACITACION OFICIAL",
                                "LICENCIA POR CAPACITACION OFICIAL",
                            ),
                            (
                                "PERMISO POR DOCENCIA UNIVERSITARIA",
                                "PERMISO POR DOCENCIA UNIVERSITARIA",
                            ),
                            ("LICENCIA POR ENFERMEDAD", "LICENCIA POR ENFERMEDAD"),
                            (
                                "LICENCIA POR SEPELIO Y LUTO (FALLECIMIENTO)",
                                "LICENCIA POR SEPELIO Y LUTO (FALLECIMIENTO)",
                            ),
                            ("PERMISO SIN GOSE DE HABER", "PERMISO SIN GOSE DE HABER"),
                            ("POR COMISION DE SERVICIO", "POR COMISION DE SERVICIO"),
                            ("POR CITUACION JUDICIAL", "POR CITUACION JUDICIAL"),
                            ("POR LACTANCIA", "POR LACTANCIA"),
                            ("OTROS (ESPECIFICAR)", "OTROS (ESPECIFICAR)"),
                        ],
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "fecha_inicio",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fecha_fin", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "duracion_dias",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_papeleta_dia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_papeleta_jefe",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_papeleta_rrhh",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado_final",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "documento_identidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filiacion.empleado",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
