# Generated by Django 4.1.5 on 2023-02-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0034_alter_papeletahora_documento_identidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="papeletahora",
            name="condicion_laboral",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="papeletahora",
            name="regimen_laboral",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
