# Generated by Django 4.1.5 on 2023-02-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0035_papeletahora_condicion_laboral_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="papeletahora",
            name="nombre_completo",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
