# Generated by Django 4.1.5 on 2023-03-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0037_alter_papeletahora_fecha_papeleta_hora_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="papeletadia",
            name="anio",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="papeletadia",
            name="condicion_laboral",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="papeletadia",
            name="dia",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="papeletadia",
            name="mes",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="papeletadia",
            name="nombre_completo",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="papeletadia",
            name="regimen_laboral",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
