# Generated by Django 4.1.5 on 2023-03-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0038_papeletadia_anio_papeletadia_condicion_laboral_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="papeletadia",
            name="fecha_fin",
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="papeletadia",
            name="fecha_inicio",
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="papeletadia",
            name="fecha_papeleta_dia",
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
