# Generated by Django 4.1.5 on 2023-03-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filiacion", "0039_alter_papeletadia_fecha_fin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="papeletadia",
            name="documento_identidad",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
